### ISSUE TITLE
Trusted Types should allow the 'none' keyword

### ISSUE THREAD

**Issue by craigfrancis** [google/csp-evaluator#33]
Trusted Types uses the keyword 'none' to show that no policies are allowed:

https://w3c.github.io/webappsec-trusted-types/dist/spec/#trusted-types-csp-directive

This is used to enforce Trusted Types restrictions (disabling unsafe APIs), without needing a policy to bypass these restrictions.

https://github.com/google/csp-evaluator/blob/e3638195ac812d61dc8ea11b5805e04e4230e2f6/checks/parser_checks.ts#L138

    if (value === '\'allow-duplicates\'' || value === '\'none\'') {

I believe this would fix the issue where [LightHouse](https://github.com/GoogleChrome/lighthouse/blob/master/package.json#L171) shows the error message `'none' seems to be an invalid keyword.`

**Comment by lweichselbaum** [comment]
Thank you very much for raising this issue!

**Comment by lweichselbaum** [comment]
NPM package updated: https://www.npmjs.com/package/csp_evaluator

**Comment by andrerferreira** [comment]
Hi, I've noticed the same problem at https://csp-evaluator.withgoogle.com perhaps the fix can make it there also.
Best regards,
A.
