### ISSUE TITLE
Add support for `navigate-to`

### ISSUE THREAD

**Issue by craigfrancis** [google/csp-evaluator#34]
While not currently enabled on [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=805886) or [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1529068), CSP3 does define the `navigate-to` directive:

https://www.w3.org/TR/CSP3/#directive-navigate-to

I think it just needs to be added to the `Directive` enum:

https://github.com/google/csp-evaluator/blob/e3638195ac812d61dc8ea11b5805e04e4230e2f6/csp.ts#L235

And maybe FETCH_DIRECTIVES, even though I don't think it's technically a fetch (returning for this document), it's still a `serialized-source-list`:

https://github.com/google/csp-evaluator/blob/e3638195ac812d61dc8ea11b5805e04e4230e2f6/csp.ts#L287

**Comment by adamraine** [comment]
@ddworken can you do an npm release for this?
