### ISSUE TITLE
Problem with latest version 1.0.2

### ISSUE THREAD

**Issue by adrianaferrugento** [google/csp-evaluator#36]
There seems to be a problem with the new version of `csp-evaluator`, I keep getting this error now:

<img width="1145" alt="Screenshot 2021-08-04 at 14 29 05" src="https://user-images.githubusercontent.com/76945696/128189556-2176a46d-afc2-4ec3-890b-85b90c7c0875.png">

**Comment by lweichselbaum** [comment]
@adamraine can you look into this?

**Comment by patrickhulce** [comment]
@lweichselbaum between 1.0.1 and 1.0.2 the location of the `dist` files for the `lighthouse` folder moved from `lighthouse/dist` to `dist/lighthouse`, this breaks lighthouse usage which relies on `lighthouse/dist` and only locked to `^1.0.1`. 

Would you be able to revert to the previous directory structure for `1.x` and only move to `dist/lighthouse` in a breaking change?

**Comment by ddworken** [comment]
See `https://unpkg.com/csp_evaluator@1.0.4/dist/lighthouse/lighthouse_checks.js`

**Comment by adrianaferrugento** [comment]
Amazing, thank you!
