### ISSUE TITLE
Claims that allowing requests to http://127.0.0.1 is a risk

### ISSUE THREAD

**Issue by BenjaminEHowe** [google/csp-evaluator#5]
I don't think I need HTTPS when requests will stay within my computer. [w3c agrees](https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy), considering http://127.0.0.1 "potentially trustworthy", and therefore most modern browsers wouldn't warn of mixed content. Please could this tool be tweaked?

**Comment by lweichselbaum** [comment]
I'm closing this as working as intended. 
Loopback addresses shouldn't be used in an production environment.
