### ISSUE TITLE
Missing *-src directives when default-src is unspecified

### ISSUE THREAD

**Issue by hansmach1ne** [google/csp-evaluator#67]
The following CSP is regarded as secure:  `Content-Security-Policy: script-src 'none'; object-src 'none'`

When `default-src` is unspecified and if any of the following directives are not present, those are therefore also not specified:

```
style-src
img-src
connect-src
font-src
media-src
frame-src
child-src
worker-src
manifest-src
prefetch-src
```

There are a couple of issues here, specifically when default-src is missing:

a) If `style-src` is explicitly not specified or `unsafe-inline`, attacker can leak parts of the HTML code with inline CSS injection.

b) if for example `img-src` is explicitly not specified, attacker can overwrite server-defined Referrer-Policy by injecting `<img>` tag with it's own `referrerpolicy` attribute and leak the whole site's URL where the injection is present. Check: `https://issuetracker.google.com/issues/332052787` for more info.

c) Firefox and some other browsers have no Dangling Markup protections in place. Which means attacker can reference his/her site via any of those *-src directives and achieve cross-site leakage.

**Comment by lweichselbaum** [comment]
Thank you for your comment. The CSP Evaluator is assessing CSPs for their ability to mitigate XSS and does not cover other use cases like mitigating data leaks.

**Comment by hansmach1ne** [comment]
This was supposed to be a request for improvement.

CSP  *-src directives are created for the exact purpose to prevent loading of external contents. The CSP's task is to prevent other issues not just XSS. 

Now, I understand this project is intended for XSS alone. however if that is the case as you mention, then why at all parse some CSP directives, You can't parse i.e style-src then at all.  If style-src is unsafe-inline, Google shouldn't say it's fine when clearly it's not!

C'mon we can do better than that.
